- 异常是程序出错，包括**编译器错误**（括号没有配对，语句少写分号，关键字拼写错误）和**运行时期错误**（空指针异常，数组下标越界）
- Throwable 所有错误的父亲
  - Error 极少出现，出现很难解决
    - VirtualMachineError
    - OutOfMemoryError
    - THreadDeath
  - Exception 经常出现，可以避免
    - UncheckedException 编译器不要求强制处理的
      - NullPointerException
      - ArrayIndexOutOfBoundsException
      - ArithmeticException
      - ClassCastException
    - CheckedException
      - IOException
      - SQLException
- 抛出异常   <====>  捕获异常
- 对于可检查异常必须捕捉或者声明
- 异常处理
  - 捕获异常
    - try：执行可能产生异常的代码
    - catch：捕获异常
    - finally：无论是否发生异常，代码都会执行
  - 声明异常
    - throws：声明可能要抛出的异常
  - 抛出异常
    - throw：手动抛出异常
- try块后可接零个或多个catch块，如果没有catch块，则必须跟一个finally块
- 使用System.exit(code)终止JVM运行，他会**屏蔽掉finally块**
- 如果try catch finally同时包含return，那么只有finally的return会执行，**其他俩被屏蔽**
- 多重catch捕获异常时，应该把最顶层Exception放到最后面，如果放到前面就会让其他catch失效
- 通过throws声明要抛出什么样的异常，通过throw将产生的异常抛出
  - 要么在本方法里面把异常处理
  - 要么自己没有能力解决这个异常，就交给上一级处理

- 如果一个方法可能会出现异常，但是没有能力处理这种异常，可以在方法声明处使用throws子句来声明抛出异常
- 为什么throws一个Exception的方法在外界调用不使用try-catch处理会报错，throws ArithmeticException,InputMismatchException就不会报错？因为这俩个属于RuntimeException，在运行时出错才会报错
- throw用来抛出一个异常，抛出的只能是可抛出类Throwable或者其子类的实例对象
  - throw出来后，如果要在本方法处理，那么用try-catch包裹
  - 如果不在本方法处理，通过throws，传递给上一级方法
- 自定义异常，继承至Exception，调用super构造器
- 异常链：捕获一个异常后抛出一个异常，逐层抛出。
  - 调用父类的重载构造器，传入第二个参数为本次接收的异常
  - 调用initCause方法
- 当子类重写父类抛出的异常方法时，声明的异常必须是父类方法声明异常或者其子类

